### ISSUE TITLE
[Bug]: sudo-flix Extension Not Functioning in Zen Browser

### ISSUE THREAD

**Issue by Darknight92228** [sussy-code/smov#101]
### What happened?

I am experiencing an issue with the sudo-flix extension when using it on Zen Browser. After installation and enabling the extension, it does not assist with finding or loading sources on the website, https://pseudo-flix.pro/.

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

1. Download the extension from this [link](https://github.com/sussy-code/browser-ext/releases/download/1.2.0/1.2.0-mwext-FIREFOX.xpi).
2. Install and enable the extension on Zen Browser.
3.	Navigate to https://pseudo-flix.pro/.
4.	Attempt to search for or load any sources.

### Other relevant information

Expected Behavior:
The extension should assist in loading the necessary sources and help with search functionality on the website.

Actual Behavior:
The extension does not work correctly in Zen Browser, failing to find or load any sources.
<img width="301" alt="image" src="https://github.com/user-attachments/assets/f6ac53c7-4c03-4f18-94b8-086c0f8597e8">

Browser Version:
Zen Browser -1.0.0-a.39 (64-bit) / MacOS-14.6.1

Additional Information:
This issue only occurs on Zen Browser. The extension works without issues on Firefox ESR, suggesting that it might be a compatibility issue with Zen Browser.

**Comment by ztpn** [comment]
Yes it's an issue with the browser not the extension, please use a different browser.
