### ISSUE TITLE
[Bug]: Not able to deploy proxy on Netlify

### ISSUE THREAD

**Issue by kuttyhub** [sussy-code/smov#109]
### What happened?

Hi 👋 ,

I tried to [deploy the proxy](https://docs.undi.rest/proxy/deploy#deploying-the-proxy) in netlify as per the doc, but I am getting the following error.

<img width="1265" alt="image" src="https://github.com/user-attachments/assets/c5d3ce90-b64e-4728-9df9-554d5f8e5c46">

this what netlify ai suggesting,
<img width="1041" alt="image" src="https://github.com/user-attachments/assets/9910fe1d-4eca-4211-96b7-9338e7c90c5f">

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. go to [deploy the proxy](https://docs.undi.rest/proxy/deploy#deploying-the-proxy)
2. click deploy to netlify
3. approve all steps and trigger the deploy

**Comment by ztpn** [comment]
Just use cf workers

**Comment by FOLLGAD** [comment]
In `Build & Deploy` -> `Build Settings`, set `Functions directory` to `.netlify`, fixes this problem
