### ISSUE TITLE
[Feature]: info button that links to tmbd

### ISSUE THREAD

**Issue by Pasithea0** [sussy-code/smov#18]
### What feature do you want to add?

I put this together. Can pr if interested
The clickable area is larger for touch input devices.

https://github.com/sussy-code/smov/assets/74743263/32007a44-5bbd-44cc-801b-eb729c5a1c57

### Why do you want to have this feature?

because is nice

**Comment by Pasithea0** [comment]
https://smov.envious.pro/

**Comment by sussy-code** [comment]
nah, we are MW this is too much of a change to the simplicity
