### ISSUE TITLE
[Bug]: Have to login everytime I restart my browser

### ISSUE THREAD

**Issue by DenuxPlays** [sussy-code/smov#23]
### What happened?

When I watch something on my selfhosted instance I get logged out when I close my browser.

### Steps to reproduce?

1. log in
2. close your browser
3. revisit the webiste

### Other relevant information

With movie-web I have not encountered this issue.
Would be great if I stayed logged in.

**Comment by DenuxPlays** [comment]
Also I have authentik do some authentication so that my instance is not public but this worked fine with movie-web and I doubt that this is the issue.

**Comment by sussy-code** [comment]
We don't provide support on self hosted instances in our GitHub, for help with that you would have to join the discord.
[Support](https://docs.sudo-flix.lol/support)
