### ISSUE TITLE
[Feature]: User whitelist

### ISSUE THREAD

**Issue by Digital39999** [sussy-code/smov#25]
### What feature do you want to add?

Would there be a way to add who we can whitelist to access the site, or pre-generate id's? Along with disabling search on main page if not logged in.

### Why do you want to have this feature?

So not everyone can just access my own instance.

**Comment by Digital39999** [comment]
Well yeah but having something in-app would be great to manage users and allow, because of unique ui. What about just disabling search without an account?

**Comment by sussy-code** [comment]
This is not feasiable, you want us to make a drastic change to the way the site is designed. sudo-flix is literally all about everyone using it.

**Comment by orphanlol** [comment]
> ### What feature do you want to add?
> Would there be a way to add who we can whitelist to access the site, or pre-generate id's? Along with disabling search on main page if not logged in.
> 
> ### Why do you want to have this feature?
> So not everyone can just access my own instance.
> 
> ### Any other details to share?
> _No response_

krill yourself

**Comment by Digital39999** [comment]
> This is not feasiable, you want us to make a drastic change to the way the site is designed. sudo-flix is literally all about everyone using it.

Drastic change you say, what if i make a pr for it, how drastic will it be then, because i dont see anything drastic in hiding a search bar until logged in and returning 404 if not allowed.

**Comment by sussy-code** [comment]
if you have coded it please send the repository link here.

**Comment by Digital39999** [comment]
> if you have coded it please send the repository link here.

Haven't but since y'all went so against it, I might as well do it myself then.

**Comment by sussy-code** [comment]
ok

**Comment by Digital39999** [comment]
> ok

So what do you think? https://github.com/Digital39999/smov

**Comment by returnkirbo** [comment]
> > ok
> 
> So, what do you think? It uses sudo-flix backend.
> 
>     * https://github.com/Digital39999/smov
> 
>     * https://github.com/Digital39999/smov-backend
> 
>     * https://dancing-fox-ffb5d1.netlify.app
> 
> 
> Also those Light animations on discover page (for cards) are pretty much not needed and just cause that scroll lag..

I'm not sure if you noticed, but I could just append ``media/tmdb-movie-929590-civil-war`` to ``https://dancing-fox-ffb5d1.netlify.app/`` and effectively bypass your login screen. I also noticed that you can just append ``browse/a`` to browse w/o logging in. 

I believe you'd be better off just using a basic HTTP auth system rather than creating a whitelist system within sudo-flix.

**Comment by Digital39999** [comment]
> > > ok
> > 
> > 
> > So, what do you think? It uses sudo-flix backend.
> > ```
> > * https://github.com/Digital39999/smov
> > 
> > * https://github.com/Digital39999/smov-backend
> > 
> > * https://dancing-fox-ffb5d1.netlify.app
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also those Light animations on discover page (for cards) are pretty much not needed and just cause that scroll lag..
> 
> I'm not sure if you noticed, but I could just append `media/tmdb-movie-929590-civil-war` to `https://dancing-fox-ffb5d1.netlify.app/` and effectively bypass your login screen. I also noticed that you can just append `browse/a` to browse w/o logging in.
> 
> I believe you'd be better off just using a basic HTTP auth system rather than creating a whitelist system within sudo-flix.

Well good to know, but its still more pain to deal with http login.
