### ISSUE TITLE
[Feature]: Move the repository to https://codeberg.org/

### ISSUE THREAD

**Issue by HereOrCode** [sussy-code/smov#27]
### What feature do you want to add?

Due to copyright issues, movie-web has been disabled by GitHub.

### Why do you want to have this feature?

Codeberg is a non-profit, community-led organization that aims to help free and open source projects prosper by giving them a safe and friendly home.

**Comment by sussy-code** [comment]
erm, i would love to do this but we wouldn't get near as much recognition and have less git features at our disposal

**Comment by Pasithea0** [comment]
Might be smart to make an archive there?

**Comment by sussy-code** [comment]
I am down do you know how?

**Comment by Pasithea0** [comment]
Maybe this?

https://codeberg.org/RanchiMall/autosync-git-repos

**Comment by heyjumanji** [comment]
No no codeberg is not supported by vercel or any other popular hosting sites like cf soo its not a good idea also if it get down we can again make another repository and continue.

**Comment by theoparis** [comment]
It sounds like this is not going to happen?

**Comment by theoparis** [comment]
> No no codeberg is not supported by vercel or any other popular hosting sites like cf soo its not a good idea also if it get down we can again make another repository and continue.

GitHub can just take down all of the related /forked repositories if they want to.
