### ISSUE TITLE
[Feature]: Proxy NSBX and spoof the origin header

### ISSUE THREAD

**Issue by devanonon** [sussy-code/smov#30]
### What feature do you want to add?

Currently NSBX doesn't work with a self-hosted frontend. This is because the request is sent straight to NSBX and not proxied. Even then, if the request was proxied it would need to set the `origin` header to `https://sudo-flix.lol`.

I've tested this locally with curl and unless the `origin` header is set to `https://sudo-flix.lol`, I get a 521. 

### Why do you want to have this feature?

NSBX is great.

If this is something you'd be open to, happy to open a PR. I think it would require a PR first to https://github.com/sussy-code/providers and then here.

Please correct me if I'm wrong. Thanks!

**Comment by sussy-code** [comment]
Bro we run NSBX why would we want people bypassing our expensive scraping API. NSBX is for [verified instances](https://docs.sudo-flix.lol/instances) only. Please abide by the usage rules of NSBX as we are looking at releasing a free version of the NSBX API.

**Comment by devanonon** [comment]
Pls sir mi familia, I didn't know!

Very fair, seems that actually the verified instances are the way to go rn rather than self-hosting then? Would the best setup be verified frontend with custom proxy entered into the settings?

Appreciate all your work <3

**Comment by sussy-code** [comment]
the best way to use sudo-flix is downloading the [browser extension](https://docs.sudo-flix.lol/extension) and using one of the verified instances.
