### ISSUE TITLE
[Bug]: Captcha token is invalid

### ISSUE THREAD

**Issue by Mubelotix** [sussy-code/smov#33]
### What happened?

I have used your backend server on my frontend and here is what users have

![image](https://github.com/sussy-code/smov/assets/42696684/6ac174f0-0734-4d10-86db-99778d6a2f7e)
![image](https://github.com/sussy-code/smov/assets/42696684/35ff3114-11da-41e0-a88f-26e46942dc2b)
![image](https://github.com/sussy-code/smov/assets/42696684/bc1e7344-e49c-43a2-a421-4448e4792ead)

**Comment by sussy-code** [comment]
Yea, you dont have the captcha token reach out on discord maybe ill whitelist you.
