### ISSUE TITLE
[Bug]: Full-screen button doesn't launch the landscape player

### ISSUE THREAD

**Issue by ghost** [sussy-code/smov#35]
### What happened?

On android (chrome), clicking on the fullscreen button in the player does not make the player go landscape, instead it plays in portrait mode. You have to rely on Android's auto-rotate feature.

### What browsers are you seeing the problem on?

Chrome

### Steps to reproduce?

1. Launch a video
2. Click fullscreen
3. Watch it go go fullscreen but play in  portrait mode

**Comment by Pasithea0** [comment]
I have encountered this on iOS too, usually a force restart or clearing cache fixes it.

**Comment by Pasithea0** [comment]
Sometimes it won't fullscreen at all. Not sure if this is an issue with sudoflix or with the browser. I have tried it on chrome, safari, and arc search on iphone

**Comment by prodlowd** [comment]
Firefox Android issue too

**Comment by Pasithea0** [comment]
I'm pretty sure this a proxy issue. I've had the same problem with other proxied media such as invidious. 

Just relaunching the browser fixes it though. But I'm not sure if there's a solution that would solve this, I could be wrong though

**Comment by ztpn** [comment]
This is more of a browser issue allegedly 
Happens only on chrome, works fine on firefox and edge for me
