### ISSUE TITLE
[Bug]: NSBX server error

### ISSUE THREAD

**Issue by heyjumanji** [sussy-code/smov#36]
### What happened?

The server is now very unstable and it shows error most of the time actually every time

**Comment by Pasithea0** [comment]
Yeah same issue. Almost no videos load anymore. It's still in development though but L for now

**Comment by K4NK4N** [comment]
same here errored everything immediately

**Comment by sussy-code** [comment]
You have to wait on the homescreen for turnstile to init (~2 secs)
