### ISSUE TITLE
[Bug]: Repeated cloudflare checks during streaming!

### ISSUE THREAD

**Issue by und3voted** [sussy-code/smov#48]
### What happened?

During streaming of any media on any server, I get the "Are you a robot?" pop up every few minutes. This destroys any immersion, its utterly annoying and altogether completely ruins the experience. ! [image](https://github.com/sussy-code/smov/assets/165563275/eec5ccea-7c11-4ac8-ad14-283876a74e59)

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Other relevant information

I am using Brave with the movie-web extension.

**Comment by sussy-code** [comment]
Stop using the extension if u want NSBX to work
