### ISSUE TITLE
[Feature]: Stream Local Files

### ISSUE THREAD

**Issue by LofracotestinoGD** [sussy-code/smov#51]
### What feature do you want to add?

if no source works with the current movie or TV show, there should be a button to browse local files and choose a video, and in the sources too there should be a button to choose.
There could also be a button in the landing page (home) to browse.

### Why do you want to have this feature?

beacause the video player of mw is really good and i don't like any other video player

### Any other details to share?

no.

**Comment by krakenftw** [comment]
Its a web application, browser cannot access and use local files directly, so no thats not possible

**Comment by JorrinKievit** [comment]
> Its a web application, browser cannot access and use local files directly, so no thats not possible

https://jsfiddle.net/dsbonev/cCCZ2/

**Comment by returnkirbo** [comment]
Hey, I managed to get local videos working with the same video component [here](https://local-player--darling-melba-9d0223.netlify.app/local/blob%3Ahttps%3A%2F%2Flocal-player--darling-melba-9d0223.netlify.app%2F889a0068-3faa-49b1-860f-b5eb79eff1b5) but **this isn't feasible**. The component that handles the video UI with controls was not intended to support the ``<video>`` element natively, although it's certainly possible to have them support ``<video>`` controls, sudo-flix isn't a video player, and you'd be much better off using an application dedicated to playing videos.
