### ISSUE TITLE
[Bug]: Last 30s of episode is skipped

### ISSUE THREAD

**Issue by prodlowd** [sussy-code/smov#64]
### What happened?

The last 30s of every episode is skipped, haven't been able to find a cause on my end. Tried using Firefox (default browser with uBlock Origin) and also tried vanilla Edge with no add-ons, but the issue still occurred.

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Steps to reproduce?

1. Press play on an episode
2. Wait or seek to the end of the episode
3. Auto-skips last 30s (give or take) of episode

**Comment by q2C6yL15ThIOScdSYnZuQn2rAPJ90hw2C8CFcjr** [comment]
> Not really a bug
> 
> ```js
> const isEnding = time >= duration - onePercent && duration !== 0;
> ```
> 
> This is how the ending is determined It basically skips one percent of the duration
> 
> We need to change this but we can't really do much

As a feature request, why not make it so you can let the end user be capable of setting their own skip time?

**Comment by ztpn** [comment]
> > Not really a bug
> > ```js
> > const isEnding = time >= duration - onePercent && duration !== 0;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is how the ending is determined It basically skips one percent of the duration
> > We need to change this but we can't really do much
> 
> As a feature request, why not make it so you can let the end user be capable of setting their own skip time?

No that is a crapy idea, just disable autoplay
we might in future implement intro and outro skip times and use those
