### ISSUE TITLE
[Bug]: When the video is on full screen and the playback bar disappears, the subtitles also disappear

### ISSUE THREAD

**Issue by Olidoc1** [sussy-code/smov#66]
### What happened?

If I turn on the video and select subtitles from the menu and put full screen and then wait for the playback bar to disappear, the subtitles disappear too. I have to have my mouse on the playback bar to see the subtitles throughout the show.

My player setting: ![image](https://github.com/sussy-code/smov/assets/33489315/1ee4046e-7f1f-4b3d-b8bb-9ecc0ec843da)

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Other relevant information

I use Brave Browser Version 1.67.123 Chromium: 126.0.6478.126

**Comment by returnkirbo** [comment]
Hi, do you have a video demonstrating the issue? Do you also have a rough idea on how you reproduced this? I've been looking at this issue for some time (as this was also reported in the Discord) and I could not seem to reproduce it.

**Comment by Karelak** [comment]
Oh, I had this issue as well I posted about it in discord, [I have a video showing the problem. ](https://imgur.com/a/UvmsNXJ)
never solved it but think it's by design how chromium browsers or at least edge browsers to my knowledge work as I have tried to remake this on safari and it doesn't happen, however I could be wrong I just have had the same problem

**Comment by Karelak** [comment]
Ok weird fix that I think currently works on latest edge, turning on the enhancement thingy that comes with edge I think makes it work fine for now, although it could not always work.

**Comment by returnkirbo** [comment]
> Oh, I had this issue as well I posted about it in discord, [I have a video showing the problem. ](https://imgur.com/a/UvmsNXJ) never solved it but think it's by design how chromium browsers or at least edge browsers to my knowledge work as I have tried to remake this on safari and it doesn't happen, however I could be wrong I just have had the same problem
> 
> I have experienced this same problem on other chromium-based browsers but currently am experiencing this on **Microsoft Edge Version 126.0.2592.81** which i believe uses **chromium 126**
> 
> Also this could also be a problem with 2 monitors when you move the mouse to a secondary monitor

There was a video demonstrating around ~1 week ago that demonstrated this issue could happen without moving your mouse onto a second monitor. 

If anyone here is reading this but is also experiencing the same issue, please feel free to reply with your Browser & version and/or a rough idea of how you can reproduce the issue.

**Comment by Olidoc1** [comment]
Hello, 

after a long hiatus, I just wanted to let you know that somehow, miraculously, things got fixed. I don't know what it was, but it's fine.

Thanks for the support anyway.

**Comment by returnkirbo** [comment]
> Hello,
> 
> after a long hiatus, I just wanted to let you know that somehow, miraculously, things got fixed. I don't know what it was, but it's fine.
> 
> Thanks for the support anyway.

Glad to hear! Very weird bug.
