### ISSUE TITLE
[Bug]: Can't login. GET or POST fail.

### ISSUE THREAD

**Issue by Fre148** [sussy-code/smov#67]
### What happened?

I'm using latest Brave Browser. Shields are turned off on Sudo-flix. I'm using an official instance with official backend.

When trying to login with the 12 word password and name, it takes some time loading but fails. The error code is the following.

> [GET] "https://backend.sudo-flix.lol/users/xxxxxxxxxxxx/progress": <no response> Failed to fetch

I tried logging in before filing these issue and the error was a POST one.

Thank you!

### What browsers are you seeing the problem on?

Chrome, Other (tell us in input box below)

### Steps to reproduce?

1. Open Sudo-flix on Brave Browser
2. Select "Cloud synchronization"
3. Input your 12 word and name
4. Click on "Login"
5. Login fails with either GET or POST "Couldn't fetch".

**Comment by bradleytechman** [comment]
The backend is currently being ddosed so anything that connects to the backend will not work quickly. I was able to login in but it takes a bit till it works

**Comment by Fre148** [comment]
Thanks for answering! Hope it gets solved :)
