### ISSUE TITLE
[Bug]: Seekbar is completely broken on edge (hyperOS) when using NSBX

### ISSUE THREAD

**Issue by Vader77Darth** [sussy-code/smov#68]
### What happened?

When using the NSBX source in edge on HyperOS, the Seekbar is always all the way and only ever says 00:00. It works on other sources but not with NSBX.
![Screenshot_2024-07-04-10-52-47-293_com microsoft emmx](https://github.com/sussy-code/smov/assets/87441738/2160d2e9-6c93-4a43-8c79-d0573ef13152)

### Steps to reproduce?

Open Sudo flix with edge.
Use the NSBX source.

### Other relevant information

This Seekbar bug has been happening even back since the movie-web days.

**Comment by returnkirbo** [comment]
What is "edge"? Could you link me the browser? Does this also happen with other browsers (ie Chrome/Firefox/etc)?

**Comment by Vader77Darth** [comment]
> What is "edge"? Could you link me the browser? Does this also happen with other browsers (ie Chrome/Firefox/etc)?

Edge is the browse I use; here is a link: https://global.app.mi.com/details?lo=ES&la=en&id=com.microsoft.emmx
I have not found this to happen with any other browsers but I dont really use many browsers so I can't confirm this is exclusive to edge.

**Comment by ztpn** [comment]
> > What is "edge"? Could you link me the browser? Does this also happen with other browsers (ie Chrome/Firefox/etc)?
> 
> Edge is the browse I use; here is a link: https://global.app.mi.com/details?lo=ES&la=en&id=com.microsoft.emmx I have not found this to happen with any other browsers but I dont really use many browsers so I can't confirm this is exclusive to edge.

edge mobile video player is kinda broken use Firefox

**Comment by Vader77Darth** [comment]
> > > What is "edge"? Could you link me the browser? Does this also happen with other browsers (ie Chrome/Firefox/etc)?
> > 
> > 
> > Edge is the browse I use; here is a link: https://global.app.mi.com/details?lo=ES&la=en&id=com.microsoft.emmx I have not found this to happen with any other browsers but I dont really use many browsers so I can't confirm this is exclusive to edge.
> 
> edge mobile video player is kinda broken use Firefox

![Screenshot_2024-07-06-09-30-11-546_com discord-edit](https://github.com/sussy-code/smov/assets/87441738/c94d12db-bb27-4b20-a879-dd5abacd13e3)

Firefox doesn't support hevc decoding so cannot use nsbx properly.
