### ISSUE TITLE
[Bug]: Cloudflare infinite loop on lg tv webOS

### ISSUE THREAD

**Issue by anna10101010** [sussy-code/smov#70]
### What happened?

Hi, fantastic site!
Cloudflare and the site work great on my iPhone however when I try on my LG TV using the built in browser, I’m stuck in an infinite ‘are you human’ loop with Cloudflare. 
Browser: NetCast on Linux
WebOS

One of the comments on the Cloudflare forum said that the website owner might need to check a setting as you might be blocking it

I also tried with your other mirror site and same issue unfortunately

![IMG_9964](https://github.com/sussy-code/smov/assets/56526102/2efbaf0d-d661-4a67-9814-654e34db34be)

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

1. Gone to the site on my tv and am immediately hit with the verify human thing that just keeps refreshing

**Comment by itzCozi** [comment]
Sorry, this is because of Cloudflare interactive challenge and it just doesn't work on some devices. Try casting to the TV or using an HDMI cord.
