### ISSUE TITLE
[Bug]: Logins not persistent when adding site as an iOS home screen shortcut

### ISSUE THREAD

**Issue by tsedan** [sussy-code/smov#73]
### What happened?

After adding the site to my iOS home screen, I can log in and the site works fine, but if I close and reopen it, I am logged out and forced to log back in. Expected behavior is to stay logged in between sessions.

### What browsers are you seeing the problem on?

Safari

### Steps to reproduce?

1. In iOS safari, open the site, click the share icon, scroll down, and press "Add to Home Screen".
2. Open the "app" that is created and log in as usual.
3. Close and reopen the app.

**Comment by itzCozi** [comment]
works fine for me?
https://cdn.discordapp.com/attachments/1124537776851927050/1263698174334206014/RPReplay_Final1721359506.mov?ex=669b2e23&is=6699dca3&hm=91f88cfce7701e8e4322e6d61f10adb7ef089d0fbb0ec9488c9ea5117ebc0b9a&

**Comment by tsedan** [comment]
I fixed the problem, but not after getting a recording of it breaking:

https://media.discordapp.net/attachments/1177690924260790274/1263702625292124221/RPReplay_Final1721359835.mov?ex=669b3248&is=6699e0c8&hm=e780c4d61fdf7e2bbdc73e38a016aa8f25946e6342f5d9669566bf3bf2775686&

Clearing website data fixed it for me. Not sure what the cause of the issue was but I'll close this anyway.
