### ISSUE TITLE
[Bug]: No Airplay for video in IOS 

### ISSUE THREAD

**Issue by alvarogalloc** [sussy-code/smov#74]
### What happened?

I used to airplay my series to my roku but now it only sends the audio, i don't know it this is intended or was a block by apple but it just happened a few weeks ago

### What browsers are you seeing the problem on?

Safari ios, Google Ios App

### Steps to reproduce?

Open any content and try to use the tv icon to use airplay

**Comment by Pasithea0** [comment]
I've noticed this as well, some sources work still however.

**Comment by ztpn** [comment]
Have you tried changing sources?

**Comment by Pasithea0** [comment]
not working at all now.
