### ISSUE TITLE
[Feature]:  API

### ISSUE THREAD

**Issue by WalkTheEarth** [sussy-code/smov#81]
### What feature do you want to add?

A simple GET or POST api to be able to get links to movies. 

### Why do you want to have this feature?

to make addons to kodi, or standalone apps, or so many other things. 

### Any other details to share?

it would be nice if you could do something like "curl api.sudo-flix.lol/search/The-truman-show" to get a link back to the truman show (the movie)

**Comment by ztpn** [comment]
By links you mean streams like mp4 and m3u8 playlists?

**Comment by WalkTheEarth** [comment]
yes.

**Comment by ztpn** [comment]
We won't host anything like that at least for now.

There was a providers-api on movie-web which you could use.
