### ISSUE TITLE
[Feature]: Watched list

### ISSUE THREAD

**Issue by PorkingMane** [sussy-code/smov#83]
### What feature do you want to add?

well.. list of stuff you already watched similar to "favorite" thing

### Why do you want to have this feature?

Because it would be cool to replace shitty IMDB to proper, cool-looking, amazing and funny site

### Any other details to share?

maybe i am dumb and it is already here but like when you local host it, but if not then would be really glad if added :)

**Comment by ztpn** [comment]
What do you mean?
We already have it
![A](https://github.com/user-attachments/assets/639ac8bb-3a57-4945-8bda-77c38dab37d5)
