### ISSUE TITLE
[Bug]: Manifest.json 403 Forbidden

### ISSUE THREAD

**Issue by absurdprofit** [sussy-code/smov#84]
### What happened?

Tried adding the app to homescreen with chrome which even supports the option for apps without a manifest.json. So it was weird to me that this wasn't available at all for your app (great app btw). Looked into the network panel and saw the manifest.json file being requested but the server was returning a 403. When I open the [URL](https://pseudo-flix.pro/assets/manifest-CuRP_CD7.json) in a separate tab however the manifest loads fine.  Judging by the fact your app is cloudflare protected I'm willing to bet this a cloudflare config issue. Not a cloudflare user so I won't be much help there. Anyways thanks.

### Steps to reproduce?

Issue can be reproduced by either visiting the application or simply sending a request to https://pseudo-flix.pro/assets/manifest-CuRP_CD7.json via postman or other similar HTTP client.

### Other relevant information

![image](https://github.com/user-attachments/assets/d7904acf-c803-43d6-8c22-6e3fb2a44170)

**Comment by ztpn** [comment]
Uh has to be smth with cf and cache, we will later remove the manifest and then favicon from waf
