### ISSUE TITLE
[Feature]: Type lables

### ISSUE THREAD

**Issue by DevoMan00** [sussy-code/smov#86]
### What feature do you want to add?

Lables in the corner of the poster indicating whether the media is hd, ts,.or a cam.

### Why do you want to have this feature?

This site/build is great for many reasons. However, I also prefer to have a good viewing experience. While some are fine with whatever content is available, cams are worse when compared to an hd file. The only problem is that the site doesn't directly indicate whether the content is what type.

**Comment by ztpn** [comment]
All media is taken directly from the sources and the only way to find out the best quality for a media item is by scraping all sources which we don't do
