### ISSUE TITLE
[Bug]: Vidsrc to error occurred

### ISSUE THREAD

**Issue by lawdefier** [sussy-code/smov#9]
### What happened?

i have tried multiple times in the past few hours but no luck whenever i try to watch a season it says we couldnt find that i kn
ow for a fact its in vidsrc to since i watched it yesterday but idk why today it doesnt even check vidsrc to just says error eccoured 

![image](https://github.com/sussy-code/smov/assets/128478459/914c26a7-94ba-408f-9cec-c363b48cee29)

### What browsers are you seeing the problem on?

google chrome

**Comment by sussy-code** [comment]
This is because we can’t scrape vidsrc without the extension get the extension or wait for NSBX

**Comment by lawdefier** [comment]
Ok, thanks for the update.
