### ISSUE TITLE
[Bug]: Unable to build on cloudflare pages

### ISSUE THREAD

**Issue by Pasithea0** [sussy-code/smov#97]
### What happened?

I think Cloudflare is ignoring the lock file and using newer package versions. Here is the log:

```
...
21:35:23.141 | /opt/buildhome/repo/src/pages/Discover.tsx
-- | --
21:35:23.142 | 24:1  error  `../components/Icon` import should occur before import of `./parts/util/PageTitle`  import/order
21:35:23.142 |  
21:35:23.142 | ✖ 1 problem (1 error, 0 warnings)
21:35:23.142 | 1 error and 0 warnings potentially fixable with the `--fix` option.
21:35:23.142 |  
21:35:23.298 | ELIFECYCLE  Command failed with exit code 1.
21:35:23.331 | Failed: Error while executing user command. Exited with error code: 1
21:35:23.341 | Failed: build command exited with code: 1
21:35:24.908 | Failed: error occurred while running build command
```

This however is not an error when building locally, due to it actually using the correct version.

Note: Building works properly without any changes on Vercel and locally.

### Steps to reproduce?

I have tested it on my personal account and with a brand-new account. Cloudflare fucks it up.
1. Fork the main branch
2. link GitHub or Gitlab to Cloudflare
3. Create the Cloudflare page
4. Deploy with ```pnpm build``` and ```/dist``` output

### Other relevant information

Workaround:
Build locally and upload dist folder as a static page.
Or
Update pnpm and packages and fix the error in logs.

**Comment by ztpn** [comment]
I just pushed a fix but we still need to figure out why is pages ignoring the lockfilee
