### ISSUE TITLE
 Media player showing errors

### ISSUE THREAD

**Issue by MemselfI** [sussy-code/smov#98]
### What happened?

```URL - /media/tmdb-movie-1129608-the-greatest-of-all-time
API - false

nsbx: notfound
Couldn't find a stream: No providers available
whvx: success
soapertv: notfound
Couldn't find a stream: Content not found
ee3: notfound
Couldn't find a stream: No watchable item found
ridomovies: failure
TypeError: Cannot read properties of undefined (reading 'items')
warezcdn: notfound
Couldn't find a stream: No streams found
insertunit: notfound
Couldn't find a stream: No result found
primewire: notfound
Couldn't find a stream: No streams found
whvx-0: failure
TypeError: Cannot read properties of undefined (reading 'filter')
```

### What browsers are you seeing the problem on?

Other (tell us in input box below)

### Steps to reproduce?

I am using Brave Browser

**Comment by ztpn** [comment]
Learn to read
THAT JUST MEANS THE ITEM IS NOT AVAILIBLE ON ANY SOURCES

**Comment by MemselfI** [comment]
> Learn to read THAT JUST MEANS THE ITEM IS NOT AVAILIBLE ON ANY SOURCES

> I know.
If item is not available on any source then why did the site showed it when searched. It should be removed.

**Comment by MemselfI** [comment]
> ![image](https://private-user-images.githubusercontent.com/96815580/368196116-a766bc85-eb5d-4c0a-8d2a-d5cbb3a49e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1ODMwNjIsIm5iZiI6MTcyNjU4Mjc2MiwicGF0aCI6Ii85NjgxNTU4MC8zNjgxOTYxMTYtYTc2NmJjODUtZWI1ZC00YzBhLThkMmEtZDVjYmIzYTQ5ZTE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDE0MTkyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2ODg1M2UyYmQyODA1YWRiZTk0YjYwODRjOTI0Y2NlOTYxMWU3YTY4OGEzNTdlZTdjOWExNjNiOGZkYzkwYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bDlE1ir3SggX1aJ3fgWWdhE58Ug6Z8udj4SI-u_9nIE)

Sorry for the misunderstanding.
